Fix warning that implicit capture of this is deprecated in C++20
fpshelper.cpp:10:48: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]

Pick-to: 6.4 6.5
Change-Id: I7f354474adce419ca6c2fffd174815fed5e58d76
Reviewed-by: Marc Mutz <marc.mutz@qt.io>