Fix warning that implicit capture of this is deprecated in C++20
fpshelper.cpp:10:48: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]

Change-Id: I7f354474adce419ca6c2fffd174815fed5e58d76
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 9bc1107b8137e6731426b27f1f73e9a20c2a5515)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>